fix: update recipe descriptions to be more informative
aws/aws-dotnet-deploy pull request #344
Opened 2021-10-01 18:34 UTC by philasmar

*Issue #, if available:*
IDE-5944

*Description of changes:*
fix: update recipe descriptions to be more informative

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-10-01 19:56 UTC, ganeshnj approved these changes

2021-10-01 20:40 UTC, 96malhar approved these changes

2021-10-01 20:50 UTC, normj requested changes
Do not put things in ALL CAPS. It looks like we are yelling at our customers and is inconsistent with Visual Studio.

Also do not say "USING DOCKER" in the recommendation because I'm pretty sure Fargate used containerd not docker to run the containers.

2021-10-06 14:27 UTC, philasmar commented
> Do not put things in ALL CAPS. It looks like we are yelling at our customers and is inconsistent with Visual Studio.
> 
> Also do not say "USING DOCKER" in the recommendation because I'm pretty sure Fargate used containerd not docker to run the containers.

Fixed

2021-10-06 19:33 UTC, closed without merging