chore: Alter option setting names in Elastic Beanstalk recipe
aws/aws-dotnet-deploy pull request #571
Opened 2022-05-23 23:17 UTC by 96malhar

*Issue #, if available:*
DOTNET-5882

*Description of changes:*
This PR makes the following changes to the Elastic Beanstalk recipe.

* Changes the top-level `BeanstalkApplication` option setting name to `Elastic Beanstalk Application`. This is done because the original option setting name (`Application Name`) was also being used to set the name of the CloudFormation stack. Using the same name to represent the different constructs can be confusing to users.
* Changes the `EnvironmentName` option setting item to a simple `string` type.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-05-23 23:57 UTC, philasmar requested changes
The beanstalk environment is intentionally done this way to avoid a breaking change. Norm and I have discussed this before and we decided against any action on the current structure.

2022-05-24 16:13 UTC, 96malhar commented
> The beanstalk environment is intentionally done this way to avoid a breaking change. Norm and I have discussed this before and we decided against any action on the current structure.

Removed the changes related to Beanstalk Environment.

2022-05-25 05:15 UTC, normj approved these changes

2022-05-25 14:45 UTC, ashovlin requested changes
Like we discussed at stand-up yesterday, could you add a unit test asserting on the current structure of the relevant Beanstalk recipe options, with a note why we shouldn't update them?

2022-05-25 15:17 UTC, 96malhar commented
> Like we discussed at stand-up yesterday, could you add a unit test asserting on the current structure of the relevant Beanstalk recipe options, with a note why we shouldn't update them?

We want to assert on the recipe structure of all the recipes and not only the Beanstalk one. This can be tackled as part of a separate story. I will go ahead and create a backlog item for it

2022-05-25 15:48 UTC, ashovlin approved these changes

2022-05-25 15:58 UTC, 96malhar commented
> > Like we discussed at stand-up yesterday, could you add a unit test asserting on the current structure of the relevant Beanstalk recipe options, with a note why we shouldn't update them?
> 
> We want to assert on the recipe structure of all the recipes and not only the Beanstalk one. This can be tackled as part of a separate story. I will go ahead and create a backlog item for it

Create DOTNET-5998 to add unit tests that assert on all recipe structures and can detect breaking changes.

2022-05-25 16:02 UTC, philasmar approved these changes

2022-05-25 16:02 UTC, merged