fix: subnets and security groups are displayed without selected vpc id in app runner
aws/aws-dotnet-deploy pull request #589
Opened 2022-06-03 02:22 UTC by philasmar

*Issue #, if available:*
DOTNET-5906

*Description of changes:*
* Updated App Runner recipe to add dependencies and validators for the VPC Connector setting so that Subnets and Security groups will no longer be displayed if a Vpc Id is not set.
* Remove orphaned function `OverrideValue` from type hints as it is not used
* Updated OptionSetting Validators to accept OptionSettingItem as a parameter
* Updated Required validator to display more information message

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-06-03 21:11 UTC, normj requested changes

2022-06-03 21:11 UTC, normj commented on src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe
> +                {
Adding this is potentially a breaking change for existing users. For example in current deployments if a user selected create a new VPC connector. Then they take this update. Unless the change this setting to true during redeployments they will lose the VPC connector.

I think we have to make this change under the guise of the tool being in preview but we should call this out in the changelog.

2022-06-06 13:28 UTC, philasmar commented on src/AWS.Deploy.CLI/Commands/TypeHints/VPCConnectorCommand.cs
> +                    UseVPCConnector = true,
At this stage, selectedVpcConnector will not be null since I do a check at the beginning to see if the user has vpc connectors in their account.

2022-06-06 16:21 UTC, normj requested changes

2022-06-06 16:21 UTC, normj commented on src/AWS.Deploy.CLI/Commands/TypeHints/VPCConnectorCommand.cs
> +                    UseVPCConnector = true,
The call above for `AskUserToChooseOrCreateNew` to have the user pick the VPC connector says it allows empty. So a user could choose empty and I assume that means we should not use VPC connector. Either that or we should not allow empty in the `AskUserToChooseOrCreateNew` call.

2022-06-06 16:24 UTC, philasmar commented on src/AWS.Deploy.CLI/Commands/TypeHints/VPCConnectorCommand.cs
> +                    UseVPCConnector = true,
Fixed

2022-06-06 16:29 UTC, normj approved these changes

2022-06-06 17:40 UTC, merged