ci: Add default encryption for CodeBuild bucket
aws/aws-dotnet-deploy pull request #664
Opened 2022-07-05 16:45 UTC by dscpinheiro

*Description of changes:* Enables server-side encryption with Amazon S3-managed keys (SSE-S3) for `CodeBuildArtifactsBucket`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-07-05 17:13 UTC, philasmar approved these changes

2022-07-07 15:52 UTC, ashovlin requested changes

2022-07-07 16:38 UTC, dscpinheiro commented on buildtools/ci.template.yml
> +      BucketEncryption:
I added a new commit removing the bucket resource: https://github.com/aws/aws-dotnet-deploy/pull/664/commits/13426d5354bf40cdbfddef2db47e5d80a0b04c8b

2022-07-15 16:10 UTC, ashovlin approved these changes

2022-07-20 15:53 UTC, merged