feat: Switch to use the --password-stdin switch when logging into docker
aws/aws-dotnet-deploy pull request #728
Opened 2022-11-10 07:16 UTC by normj

*Description of changes:*
When the deploy tool shells out to the docker CLI use the `--password-stdin` switch instead of `--password`. This removes the following warning messages when pushing container images to ECR.

```
Pushing the docker image to ECR repository...
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-10 17:15 UTC, philasmar requested changes
The change looks good. However, new warnings have been introduced due to nullability. Could you please have a look?

2022-11-10 23:51 UTC, normj commented
> The change looks good. However, new warnings have been introduced due to nullability. Could you please have a look?

Fixed the warnings.

2022-11-11 16:07 UTC, philasmar approved these changes

2022-11-14 16:52 UTC, ashovlin approved these changes

2022-11-14 17:56 UTC, merged