Fix: Display correct versioning info
aws/aws-dotnet-deploy pull request #832
Opened 2024-06-03 20:02 UTC by 96malhar

*Description of changes:*
Currently, the output from the `--version` switch is suffixed with the git commit hash which is not desirable.
![image](https://github.com/aws/aws-dotnet-deploy/assets/36622308/c56a5547-4eef-40e1-bee9-47685972605f).

This PR fixes the output of the `--version` switch so that it reflects the actual assembly version without the commit hash
![image](https://github.com/aws/aws-dotnet-deploy/assets/36622308/e3a8f6ea-2f8a-4a24-a792-9f5aff6a5a9e)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-03 21:17 UTC, normj approved these changes

2024-06-11 13:52 UTC, philasmar requested changes
Changes look good. However, you need to add a unit test to improve the code coverage of the new code path.

2024-06-12 22:35 UTC, 96malhar commented
> Changes look good. However, you need to add a unit test to improve the code coverage of the new code path.

Added new integration test to exercise the new logic.

2024-06-13 15:52 UTC, philasmar approved these changes

2024-06-13 15:53 UTC, merged