chore: Update the version of Amazon.CDK.Lib referenced by the recipe projects
aws/aws-dotnet-deploy pull request #885
Opened 2024-12-03 17:29 UTC by 96malhar

*Description of changes:*
This PR  updates the version of `Amazon.CDK.Lib` referenced by the recipe projects.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-12-04 15:34 UTC, philasmar requested changes
PR needs a change file

2024-12-05 17:52 UTC, 96malhar commented
> PR needs a change file

Done

2024-12-06 21:25 UTC, philasmar approved these changes

2024-12-09 18:22 UTC, gcbeattyAWS approved these changes

2024-12-30 17:06 UTC, merged